"use client";

import { useEffect, useState } from "react";

/**
 * Shows when the page was last regenerated by Next.js ISR.
 *
 * The `iso` timestamp is captured on the server at render time, which —
 * because every page render also re-runs every Pendo aggregation — is
 * effectively when the displayed data was last refreshed.
 *
 * The component shows:
 *   1. an absolute UTC date (stable for every viewer, no timezone surprises)
 *   2. a live "x ago" pill that updates every 30 seconds in the browser
 */
export function LastRefreshed({ iso }: { iso: string }) {
  const date = new Date(iso);
  const [now, setNow] = useState<number>(() => date.getTime());

  useEffect(() => {
    setNow(Date.now());
    const t = setInterval(() => setNow(Date.now()), 30_000);
    return () => clearInterval(t);
  }, []);

  const ago = relativeAgo(now - date.getTime());
  const absolute = formatAbsolute(date);

  return (
    <span title={date.toUTCString()} className="tabular-nums">
      Updated {absolute} · <span className="text-pendo-pink">{ago}</span>
    </span>
  );
}

function pad(n: number) {
  return n.toString().padStart(2, "0");
}

function formatAbsolute(d: Date) {
  // Apr 27, 2026 · 07:07 UTC — short, unambiguous, locale-stable.
  const month = d.toLocaleString("en-US", { month: "short", timeZone: "UTC" });
  const day = d.getUTCDate();
  const hh = pad(d.getUTCHours());
  const mm = pad(d.getUTCMinutes());
  return `${month} ${day}, ${hh}:${mm} UTC`;
}

function relativeAgo(ms: number) {
  if (ms < 0 || ms < 30_000) return "just now";
  const minutes = Math.floor(ms / 60_000);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) {
    const m = minutes % 60;
    return m ? `${hours}h ${m}m ago` : `${hours}h ago`;
  }
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}
