/**
 * The full Customer Engineer roster the dashboard is measuring adoption
 * against. Update this list when CEs join or leave.
 *
 * Names are matched against Pendo `metadata.agent.full_name` for visitors
 * active in the Pulse app over the last 30 days. Matching is tolerant:
 *   1. exact normalized full-name match (lowercase + alphanumeric only), then
 *   2. first-name + last-name fallback (so "John A. Maybee" matches
 *      "John Maybee" and vice versa).
 */
export const CE_ROSTER: readonly string[] = [
  "Christian Gonzales",
  "Vaughn Maxson",
  "Jordan Penn",
  "Caitlin Edberg",
  "John Rix",
  "Gavin Saldanha",
  "Matt Kerbawy",
  "Todd Stoffer",
  "Katie Trafford",
  "Felipe Melo",
  "Stephanie Huynh",
  "Ben DeSollar",
  "John Maybee",
  "Ricardo Primon",
  "Pamela Gutierrez",
  "Susie Taylor",
  "James Kirby",
  "Kendall Nelson",
  "Andrew Galley",
  "Kevin Lovinger",
  "Josh Royse",
  "Josh Jones",
  "Jamie Campbell",
  "Hannah Ellis",
  "John Walenty",
  "Jacqueline Hundley",
  "Caitlyn Zoufaly",
  "Manish Kumar",
  "Da-Me Kim",
  "Visa Gopalakrishnan",
  "Tom Charland",
  "Jenna Abdo",
  "Alexis Ordona",
  "Alec Shaffer",
  "Jasper Baure",
  "Gracen McGuire",
  "Lahdan Scarbrough",
  "Luci Franca",
  "Brandon Runkel",
  "Caitlin Luna",
  "Mckenzie Bowden",
  "Brent Parsons",
  "Grace McSweeney",
  "Hannah Hogan",
  "Eric Tatum",
  "Zackary Slater",
  "Forrest Moog",
  "Hiltsje Smilde",
  "Holly Cornelius",
  "Matt Manasco",
  "Nancy Laliberte",
  "Zoe Balmy",
  "Zach Cheek",
  "Lizzy McKinnon",
  "Janell Lindberg",
  "Carolynn Rodon",
  "Melissa Cooper",
  "Eric Wright",
  "Dave Dallmer",
  "Denise Grove",
  "Alli Bordogna",
  "Angela Roedersheimer",
  "Meghan McFarland",
  "Mollie Carrison",
  "Cutty Reynolds",
  "Alana Pennino",
  "Jack Purvis",
  "Dagny Wise",
  "Eamon Barisone",
  "Adrian Mendoza",
  "Kannan Sivagnanam",
  "Christopher Mahoney",
  "Caleb Love",
  "Emily Miller",
  "Nathan Schroeder",
  "Alexandra Murphy",
  "McKenna Claffey",
  "Emily Anastasi",
  "Erica Eveld",
  "Anna Mullins",
  "Kross Pham",
  "Simon Adler",
  "Sameer Khiroya",
  "Charlie Holden",
  "Aldo Manella",
  "Jay Shallcrass",
  "Nate Ascott",
  "Doireann Marron",
  "Alessia Cavallo",
  "Sebastian Zsifkov",
  "Davila Thompson",
  "Chris Schroeck",
  "Raad Alani",
  "Nikhil Sathyanarayana",
  "Iciar Gonzalez San Juan",
  "Tom Dowdeswell",
  "Tom Day",
  "Liam Richardson",
  "Sam Arman",
  "Elle Meyer",
  "Dustin Koch",
  "Brent Varnell",
];
